[module]
name = "Rescile Asset Editor"
url = "https://github.com/rescile/asset-editor-module"
version = "0.0.4"
description = "A standalone CSV editor application module for Asset Inventory. Needs rescile enterprise!"
rescile_version = ">=0.1.138"
